# Project information
site_name: HERE XYZ - Open Documentation
site_description: Make great maps easier
site_author: The HERE XYZ Team
site_url: https://www.here.xyz/
site_dir: ../site

# Repository
repo_name: heremaps/xyz-documentation
repo_url: https://github.com/heremaps/xyz-documentation
#edit_uri:

# Copyright
copyright: 'Copyright &copy; 2018-2020 HERE Europe B.V.'

# Configuration
theme:
  name: null
  custom_dir: ../material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: here
    accent: here
  font:
    text: Fira Sans
    code: Fira Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.svg

# Customization
extra:
  social:
    - type: globe
      link: http://www.here.com/
    - type: github-alt
      link: https://github.com/heremaps
    - type: slack
      link: https://here-xyz.slack.com

# Page tree
nav:
  - Introduction: docs/index.md
  - Getting Started: docs/getting-started.md
  - XYZ Studio:
      - Quick Tour: docs/studio/topics/index.md
      - Navigating: docs/studio/topics/navigating.md
      - Data: docs/studio/topics/data.md
      - Styling: docs/studio/topics/styles.md
      - Publishing: docs/studio/topics/publish.md
  - XYZ APIs:
      - XYZ Hub API:
          - Overview: docs/api/index.md
          - Manage Tokens: docs/api/getting-token.md
          - Quick Start:
              - Acquiring Credentials: docs/api/quickstart/acquiringcredentials.md
              - Read Spaces: docs/api/quickstart/readspaces.md
              - Create a Space: docs/api/quickstart/createspace.md
              - Write to a Space: docs/api/quickstart/writetospace.md
              - Using Activity Log: docs/api/quickstart/activitylog.md
          - Concepts:
              - GeoJSON Basics: docs/api/concepts/geojsonbasics.md
              - Namespaces: docs/api/concepts/namespaces.md
              - Tags and Tagging: docs/api/concepts/tags.md
              - Tiles: docs/api/concepts/tiles.md
              - JSON Schema: docs/api/concepts/jsonschema.md
          - Walkthrough:
              - Creating a Space: docs/api/walkthrough/creatingaspace.md
              - Adding and Deleting Features: docs/api/walkthrough/addinganddeleting.md
              - Search by Bounding Box: docs/api/walkthrough/searchbyboundingbox.md
              - Search by Tags: docs/api/walkthrough/searchbytags.md
              - Iterate over Features: docs/api/walkthrough/iterateoverfeatures.md
              - Use Schema Validation: docs/api/walkthrough/schemavalidation.md
          - Developer Guide:
              - Working with Spaces: docs/api/devguide/workwithspaces.md
              - Working with Features: docs/api/devguide/workwithfeatures.md
              - Tagging: docs/api/devguide/tagging.md
              - Accessing Features: docs/api/devguide/accessingfeatures.md
              - Search for Features: docs/api/devguide/propertiessearch.md
              - Spatial Search for Features: docs/api/devguide/spatialsearch.md
              - Adjust searchable properties: docs/api/devguide/searchableproperties.md
              - Using Clustering: docs/api/devguide/usingclustering.md
              - Working with Activity Log: docs/api/devguide/activitylogguide.md
              - Common Errors: docs/api/devguide/commonerrors.md
          - API Reference: docs/api/apireference.md
          - Useful Links: docs/api/links.md
      - XYZ Maps JS:
          - Overview: docs/ui/index.md
          - Getting started: docs/ui/gettingstarted.md
          - Display your space: docs/ui/yourxyzspace.md
          - Style your data: docs/ui/styleyourdata.md
          - Add interactivity: docs/ui/tapfeature.md
  - Tools:
      - HERE CLI:
          - Overview: docs/cli/topics/index.md
          - Commands: docs/cli/topics/cli.md
          - Shapefiles: docs/cli/topics/shapefiles.md
          - Hexbins: docs/cli/topics/hexbins.md
      - XYZ Space Invader: docs/cli/space-invader/index.md
      - GeoJSON Viewer:
          - Overview: docs/li/viewer-tool/index.md
          - GeoJSON Basics: docs/api/concepts/geojsonbasics.md
          - Advanced Features: docs/cli/viewer-tool/advanced.md
      - Open Datasets:
          - Buildings: docs/cli/topics/microsoft-buildings.md
  - Releases:
      - Release notes: docs/release-notes.md
  - Tutorials:
      - https://developer.here.com/tutorials?category=HERE%2BStudio%2Band%2BData%2BHub

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# google_analytics: ['UA-119781446-1', 'techpreview.xyz']
